version: '3'
services:
  app:
    image: user-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB: mongodb://db/user_service__service_test
      KEY: "my secret key"
  db:
    image: mongo
